// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2uAyBMurPSsIz-3I5NdUVVmgBM8TLsTY',
    appId: '1:829455006623:web:9f87373bb98bdef8f09baa',
    messagingSenderId: '829455006623',
    projectId: 'garage-auto-1a344',
    authDomain: 'garage-auto-1a344.firebaseapp.com',
    storageBucket: 'garage-auto-1a344.appspot.com',
    measurementId: 'G-1QMWMJ2GLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvbXTx3mqY0pU3aNzcfrKrrprnJk0Q8G4',
    appId: '1:829455006623:android:cb8dc6cf7de08d65f09baa',
    messagingSenderId: '829455006623',
    projectId: 'garage-auto-1a344',
    storageBucket: 'garage-auto-1a344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4DGW45NbzSglAHrdK3eeRsMMooftwSjA',
    appId: '1:829455006623:ios:e4cc59c5fd81ca33f09baa',
    messagingSenderId: '829455006623',
    projectId: 'garage-auto-1a344',
    storageBucket: 'garage-auto-1a344.appspot.com',
    androidClientId: '829455006623-l4nb6qqs1pk7kh9hsuvtcj93svn0qgd2.apps.googleusercontent.com',
    iosClientId: '829455006623-6o6evr8kqeauapjflcr645btbt3loevg.apps.googleusercontent.com',
    iosBundleId: 'com.example.garageAuto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4DGW45NbzSglAHrdK3eeRsMMooftwSjA',
    appId: '1:829455006623:ios:e4cc59c5fd81ca33f09baa',
    messagingSenderId: '829455006623',
    projectId: 'garage-auto-1a344',
    storageBucket: 'garage-auto-1a344.appspot.com',
    androidClientId: '829455006623-l4nb6qqs1pk7kh9hsuvtcj93svn0qgd2.apps.googleusercontent.com',
    iosClientId: '829455006623-6o6evr8kqeauapjflcr645btbt3loevg.apps.googleusercontent.com',
    iosBundleId: 'com.example.garageAuto',
  );
}
